# SPDX-FileCopyrightText: Andrei Gherzan <andrei.gherzan@huawei.com>
#
# SPDX-License-Identifier: MIT

name: Mirrors

on: [ push, delete, create ]

concurrency:
  group: git-mirror-me

jobs:
  yocto-mirror:
    name: Yocto Git Mirror
    runs-on: [self-hosted, Linux]
    steps:
      - uses: agherzan/git-mirror-me-action@v1.0.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.YOCTO_META_RASPBERRYPI_SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.YOCTO_META_RASPBERRYPI_SSH_KNOWN_HOSTS }}
        with:
          destination-repository: "git@push.yoctoproject.org:meta-raspberrypi"
